import "@/app/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import LeftSidebar from "@/components/shared/LeftSidebar";
import Topbar from "@/components/shared/Topbar";
import RightSidebar from "@/components/shared/RightSidebar";
import Bottombar from "@/components/shared/Bottombar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Threads",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
 
  return (
    <body className={inter.className}>
      <Topbar />
      <main className="flex flex-row">
        <LeftSidebar />
        <section className="main-container">
          <div suppressHydrationWarning={true} className="w-full max-w-4xl">
            {children}
          </div>
        </section>
        <RightSidebar />
      </main>
      <Bottombar />
      <ToastContainer />
    </body>
  );
}
